const jobs = [
  {
    id: 1,
    company: "Citi",
    title: "Java Developer - C10 - Pune",
    location: "Pune",
    type: "Hybrid",
    experience: "2 - 4 Years Exp",
    skills: ["Java", "Spring", "Hibernate", "Microservice", "SQL"],
  description: "The Applications Development Programmer Analyst is an intermediate level position...",
  },
  {
    id: 2,
    company: "Goldman Sachs",
    title: "Global Investment Research",
    location: "Bengaluru",
    type: "Onsite",
    experience: "3 - 5 Years Exp",
    skills: ["Java", "JavaScript", "ReactJS", "AngularJS", "Node.js"],
    description: "Join our global investment team and develop enterprise-grade solutions...",
  },
  {
    id: 3,
    company: "Amazon",
    title: "Backend Developer - SDE II - Hyderabad",
    location: "Hyderabad",
    type: "Remote",
    experience: "3 - 5 Years Exp",
    skills: ["Node.js", "Express", "MongoDB", "AWS"],
    description: "Work with a fast-paced backend team on scalable AWS infrastructure...",
  },
  {
    id: 4,
    company: "Google",
    title: "Frontend Engineer - L3 - Bangalore",
    location: "Bengaluru",
    type: "Hybrid",
    experience: "2 - 4 Years Exp",
    skills: ["React", "TypeScript", "Redux", "Next.js"],
    description: "Design and implement sleek, performant user interfaces for Google Ads products...",
  },
  {
    id: 5,
    company: "Microsoft",
    title: "Full Stack Developer - C10 - Noida",
    location: "Noida",
    type: "Onsite",
    experience: "3 - 6 Years Exp",
    skills: ["C#", ".NET", "SQL Server", "React"],
    description: "Responsible for building and maintaining enterprise full stack applications...",
  },
  {
    id: 6,
    company: "Wells Fargo",
    title: "DevOps Engineer - Pune",
    location: "Pune",
    type: "Hybrid",
    experience: "4 - 6 Years Exp",
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
    description: "Help automate infrastructure and CI/CD for enterprise banking solutions...",
  },
  {
    id: 7,
    company: "Infosys",
    title: "Java Developer - L2 - Chennai",
    location: "Chennai",
    type: "Onsite",
    experience: "2 - 5 Years Exp",
    skills: ["Java", "Spring Boot", "MySQL"],
    description: "Join a dynamic delivery team working on Java-based enterprise applications...",
  },
  {
    id: 8,
    company: "TCS",
    title: "Cloud Engineer - Hyderabad",
    location: "Hyderabad",
    type: "Remote",
    experience: "3 - 7 Years Exp",
    skills: ["Azure", "Terraform", "CI/CD", "Linux"],
    description: "Work on cloud migration projects for top global clients...",
  },
  {
    id: 9,
    company: "Capgemini",
    title: "React Developer - Mumbai",
    location: "Mumbai",
    type: "Hybrid",
    experience: "2 - 4 Years Exp",
    skills: ["React", "Redux", "JavaScript", "REST APIs"],
    description: "Build and support modern UI components for banking dashboards...",
  },
  {
    id: 10,
    company: "Accenture",
    title: "Node.js Engineer - Pune",
    location: "Pune",
    type: "Onsite",
    experience: "3 - 5 Years Exp",
    skills: ["Node.js", "GraphQL", "PostgreSQL"],
    description: "Develop APIs for high-traffic enterprise portals using modern backend stacks...",
  },
  {
    id: 11,
    company: "HCLTech",
    title: "Angular Developer - Chennai",
    location: "Chennai",
    type: "Onsite",
    experience: "2 - 3 Years Exp",
    skills: ["Angular", "RxJS", "TypeScript", "REST APIs"],
    description: "Develop dynamic and modular Angular-based frontend components...",
  },
  {
    id: 12,
    company: "IBM",
    title: "Java Developer - Bangalore",
    location: "Bengaluru",
    type: "Hybrid",
    experience: "3 - 6 Years Exp",
    skills: ["Java", "Spring Boot", "Kafka"],
    description: "Design and develop microservices for global financial products...",
  },
  {
    id: 13,
    company: "Wipro",
    title: "Python Developer - Hyderabad",
    location: "Hyderabad",
    type: "Remote",
    experience: "4 - 8 Years Exp",
    skills: ["Python", "Django", "REST", "MySQL"],
    description: "Responsible for developing REST APIs and backend logic for SaaS apps...",
  },
  {
    id: 14,
    company: "Zoho",
    title: "SDE - Chennai",
    location: "Chennai",
    type: "Onsite",
    experience: "1 - 3 Years Exp",
    skills: ["Java", "JavaScript", "MySQL"],
    description: "Work with cross-functional teams to deliver performant SaaS tools...",
  },
  {
    id: 15,
    company: "Freshworks",
    title: "Full Stack Engineer - Chennai",
    location: "Chennai",
    type: "Hybrid",
    experience: "2 - 4 Years Exp",
    skills: ["React", "Node.js", "MongoDB"],
    description: "Own features end-to-end on a collaborative product team...",
  },
  {
    id: 16,
    company: "CRED",
    title: "Backend Engineer - Bangalore",
    location: "Bengaluru",
    type: "Onsite",
    experience: "3 - 5 Years Exp",
    skills: ["Go", "Redis", "PostgreSQL", "Kafka"],
    description: "Build fast, reliable backend services for CRED's core payments systems...",
  },
  {
    id: 17,
    company: "PhonePe",
    title: "Software Engineer - Pune",
    location: "Pune",
    type: "Hybrid",
    experience: "2 - 4 Years Exp",
    skills: ["Kotlin", "Java", "REST APIs", "Spring Boot"],
    description: "Join a product team focused on building India-first financial solutions...",
  },
  {
    id: 18,
    company: "Paytm",
    title: "Frontend Developer - Noida",
    location: "Noida",
    type: "Onsite",
    experience: "1 - 3 Years Exp",
    skills: ["ReactJS", "Redux", "Material UI"],
    description: "Develop reusable UI components and collaborate with UX teams...",
  },
  {
    id: 19,
    company: "Flipkart",
    title: "DevOps Engineer - Bangalore",
    location: "Bengaluru",
    type: "Remote",
    experience: "4 - 6 Years Exp",
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins"],
    description: "Be part of the infra team powering India’s leading e-commerce platform...",
  },
  {
    id: 20,
    company: "Zomato",
    title: "Platform Engineer - Gurgaon",
    location: "Gurgaon",
    type: "Hybrid",
    experience: "3 - 5 Years Exp",
    skills: ["Node.js", "Redis", "MongoDB", "Kubernetes"],
    description: "Scale microservices and platform infra for millions of daily users...",
  },
];

export default jobs;
